### ISSUE TITLE
Feature request: resize and color based on time/s of launching

### ISSUE THREAD

**Issue by jongo-jingaro** [SubhamTyagi/Last-Launcher#1]
I am a user, don't know programming. This is just how I think Last-Launcher should be.
- font resize based on how many times of particular app is launched (i.e. often used app shortcut font will be bigger)

- font random color based on how many times of particular app is launched (i.e. often used app shortcut font will be brighter)

- font color change with time like https://github.com/urtxintxa/HexColorTime

- also, good launcher example is https://github.com/vackosar/search-based-launcher

**Comment by SubhamTyagi** [comment]
Thanks for your suggestions.
1. Icon resize count is implemented in current version (i.e. 0.1)
2. Random font might confuse user as every time user see new color this will also hard to remember (i tested it. This confused me also. it was hard to locating the Apps). This will be optional and user will enable it from settings.
3. Font color with time (good for background purpose)
