### ISSUE TITLE
Can't select files to restore 

### ISSUE THREAD

**Issue by psychoreactorq** [SubhamTyagi/Last-Launcher#104]
When this app calls the function to open and restore backups, there is a text string that determines what files may be selected. The current setting blocks me from restoring backups altogether. I know these details because I worked on it already, but I lost the changes and can't currently recompile to test it. 
![Screenshot_20201210-201712](https://user-images.githubusercontent.com/194158/101853849-ff6b8f80-3b25-11eb-8096-2876f16be2f3.png)

**Comment by btimofeev** [comment]
https://github.com/SubhamTyagi/Last-Launcher/blob/2abed1233d9c38a8b70d7675fd6c239a6a7c8a3e/app/src/main/java/io/github/subhamtyagi/lastlauncher/LauncherActivity.java#L943 must be chooseFile.setType("*/*");

**Comment by Sbgodin** [comment]
It's exactly the same behavior I saw.
