### ISSUE TITLE
Keeps forgetting it's the default launcher

### ISSUE THREAD

**Issue by githupper** [SubhamTyagi/Last-Launcher#125]
On occasion when installing some apps, Last Launcher will forgetting it's the default launcher and the original launcher ends up being used. Happens on both GrapheneOS and CalyxOS. 

The apps installed that reset the launcher default can be apps like Twidere or Element which should not reset the launcher default nor crash Last Launcher.

**Comment by SubhamTyagi** [comment]
This was because of Crashing the launcher on updating some apps.

**Comment by pbgapski** [comment]
I have seen this as well. I am on android 11 (lineageos). 

After installing app from google play, home goes back to built-in launcher. I set it back as default launcher on settings.

Next I installed another app as a test from play store (Open Camera). No problem. Removed the app. Still fine. Installed app (Open Camera) from f-droid, and default launcher setting was lost again, reverted to built-in launcher. After I set it back as default launcher once more, everything works.
