### ISSUE TITLE
Font sizing improvements

### ISSUE THREAD

**Issue by janPasi** [SubhamTyagi/Last-Launcher#13]
This is a cool piece of software, here's my 2 cents for the future development:

1) While for some users it's probably convenient to have the launcher increase the font size based on use frequency of the app (#1), there should be a way to disable this behaviour. I'd prefer to set the sizes of the apps myself and not have the launcher touch them after that.

2) When the size of the app font gets large enough for the app title to span across multiple lines the justification of the title in the launcher gets "weird". Maybe an option to "lock" the size so that it doesn't grow to the point where more than one line would be required?

**Comment by SubhamTyagi** [comment]
Thanks for your valuable suggestions. I will implement this next preview release.
