### ISSUE TITLE
Metadata translation license

### ISSUE THREAD

**Issue by comradekingu** [SubhamTyagi/Last-Launcher#143]
Is there a reason why only the metadata (fastlane) translations are licensed GPLv3-only,
and not GPLv3+

https://hosted.weblate.org/projects/last-launcher/store-metadata/#information

As this seems to be in error, can I change it to GPLv3+?

**Comment by SubhamTyagi** [comment]
>As this seems to be in error, can I change it to GPLv3+?
Yes

**Comment by comradekingu** [comment]
Top stuff, fixed in https://hosted.weblate.org/projects/last-launcher/#information
