### ISSUE TITLE
[Feature Request] Chinese Pinyin support for App Searching

### ISSUE THREAD

**Issue by 2catycm** [SubhamTyagi/Last-Launcher#150]
# Feature Request: Chinese Pinyin support for App Searching

Dear @SubhamTyagi,
    I am Ye Canming, a student developer from Southern University of Science and Technology, China. 
I am writing to suggest you to add Chinese Pinyin support for App Searching feature into Last-Launcher.
Chinese Pinyin, or Chinese phonetic alphabet, is one of the standard ways for Chinese people to 
- type Chinese with ascii standard keyboard, 
- help learn Chinese pronunciation, 
- using Chinese words with special meaning that does not have an appropriate English translation while writing an English article.

In many android apps, pinyin is used to accelerate searching. For example, it is
- used in WeChat and telephone book to search people's names.
- used in Windows and MIUI-launcher to search Apps or files.

I believe if Last-Launcher has this feature too, it would be a more powerful Android Launcher.

In this [PR](https://github.com/SubhamTyagi/Last-Launcher/pull/149), I chose this [tiny-pinyin library](https://github.com/promeG/TinyPinyin) to implement the feature I mentioned above.
I think this library is suitable for this feature in two aspects. 
- Firstly, it is so tiny and fast that Last Launcher would not be heavier after adding it, 
- Moreover, it is tested to be accurate on App names after some dictionary modifications. I wrote some JUnit test to verify that.

Looking forward to your reply.
Yours, Ye Canming

**Comment by SubhamTyagi** [comment]
@2catycm Thanks dude. Great work. 
After adding this feature how much bigger is apk file (release version) in size?

**Comment by 2catycm** [comment]
> @2catycm Thanks dude. Great work. After adding this feature how much bigger is apk file (release version) in size?

It is 197.3KB using Android Studio->Build->Generate Signed Apk
![image](https://user-images.githubusercontent.com/41530341/164510309-d251fca1-b904-405c-a3b0-8e3b8d971ea4.png)

**Comment by 2catycm** [comment]
Before the commits, it was 168.1KB
![image](https://user-images.githubusercontent.com/41530341/164511043-f7719578-40ba-405f-b28e-fc82936fd43f.png)
The 30kb is some kind of dictionary compiled with java code into classes.dex
