### ISSUE TITLE
[Bug]Button translation error

### ISSUE THREAD

**Issue by TimothyTian** [SubhamTyagi/Last-Launcher#157]
I am a Chinese user, when I used this app, I found that in the case of Chinese, click on the Setings-Sort Apps By-Name. The Chinese translation of ''name'' is wrong. It should be "名称", not "明朝". I think I already solve this problem, can I give a pr to it?

**Comment by SubhamTyagi** [comment]
Translation is managed by weblate(see redme file). So translate this string (or others) on weblate. 
Thanks.
