### ISSUE TITLE
FR: Sort apps by display name, groups ,categories etc. 

### ISSUE THREAD

**Issue by Frenzie** [SubhamTyagi/Last-Launcher#16]
Thanks for implementing #3! Unfortunately it's not quite working as I expected. It's useful to clarify vague app names or to shorten them (e.g., `Translator` is the Microsoft Translator, `Banking` is the ING banking app, etc.) but apps aren't sorted by their new display names.

**Comment by SubhamTyagi** [comment]
yes,after renaming apps are not sorted.  Just wait for a few releases. Sorting of apps will be implement in various ways(by categories,by app names, by usage times, by user defined:)

**Comment by Frenzie** [comment]
Sounds good! For user defined a sorting name might be of interest. That way instead of having to drag apps around manually, one could use something like `prefix.[AppName]` as a sorting name to group apps together.

Unless category is user editable. But as something from the app/store/whatever it seems less useful to me. :-)

**Comment by SubhamTyagi** [comment]
https://github.com/SubhamTyagi/Last-Launcher/issues/9#issuecomment-546698345
