### ISSUE TITLE
[Feedback] Default fonts

### ISSUE THREAD

**Issue by SubhamTyagi** [SubhamTyagi/Last-Launcher#19]
The system default font rendering is not elegant and impressive for this launcher. As a feature launcher must have a options to change fonts and have its own default fonts, for this i have implemented a option for this. 

On my phone i used 'Google Product sans fonts' as you can see in screenshots. As this font is proprietary and can't be used in F-droid app. So App have a requirement of  open source elegant, impressive fonts for this launcher. 

Could you suggest the best appropriate font? 
I will be thankful of your valuable suggestions.
 

Edit 1:  i have commented some screenshots of some fonts. if you think anyone of these is well suitable for launcher kindly comment that or you can upload your fonts screenshots.

**Comment by esmoak** [comment]
How about Noto Sans and Noto Serif?

I believe those were designed to look good across multiple languages so that would be a good starting place, in my opinion.

**Comment by SubhamTyagi** [comment]
check your fonts in this release
[Last-Launcher-release-0.3-20191021235020.zip](https://github.com/SubhamTyagi/Last-Launcher/files/3752400/Last-Launcher-release-0.3-20191021235020.zip)

**Comment by esmoak** [comment]
The font looks good. And I love all the other changes.

Am I supposed to have the option to change the font? When I click fonts, it opens my file manager and looks for fonts on my device.

**Comment by SubhamTyagi** [comment]
@esmoak 
>Am I supposed to have the option to change the font to one provided by the apk? When I click fonts, it opens my file manager.

Long click on empty area you will get Global menu where you can find the fonts and other settings.

**Comment by SubhamTyagi** [comment]
Raleway fonts 
![Raleway](https://i.imgur.com/UKMOxA4.png)

**Comment by SubhamTyagi** [comment]
quickland fonts

![Quick land](https://i.imgur.com/8xjadbx.png)

**Comment by SubhamTyagi** [comment]
open sans
![open sans](https://i.imgur.com/KdW5jV0.png)

**Comment by SubhamTyagi** [comment]
asimov fonts


![asimov](https://i.imgur.com/p1qDW7I.png)

**Comment by SubhamTyagi** [comment]
azonix fonts

![azonix](https://i.imgur.com/jbGbBou.png)

**Comment by SubhamTyagi** [comment]
moneserrat fonts
![moneserrat](https://i.imgur.com/zZpDB71.png)

**Comment by SubhamTyagi** [comment]
texgyreadventure fonts
![texgyreadventure](https://i.imgur.com/uHydRIC.png)

**Comment by SubhamTyagi** [comment]
glacial fonts
![glacial](https://i.imgur.com/VeR1olN.png)

**Comment by SubhamTyagi** [comment]
cello sans
![cello sans](https://i.imgur.com/4Ak48RO.png)

**Comment by SubhamTyagi** [comment]
comforta fonts
![comforta](https://i.imgur.com/TGlxmJf.png)

**Comment by SubhamTyagi** [comment]
avrile sans

![avrile sans](https://i.imgur.com/2QETEc5.png)

**Comment by SubhamTyagi** [comment]
@esmoak 

noto sans

![noto sans](https://i.imgur.com/o2NkDyP.png)


noto serif

![noto serif](https://i.imgur.com/A7QRmOY.png)

**Comment by esmoak** [comment]
@SubhamTyagi

It doesn’t let me select a font. 

1) long click black area
2) select fonts
3) phone requests permission to access files on device
4) allow permission
5) launcher opens the built in android file manager

Android 8.0Huawei  BND-L34
