### ISSUE TITLE
Feature request: allow rotation

### ISSUE THREAD

**Issue by trevorparsons** [SubhamTyagi/Last-Launcher#20]
Please considering including a settings option to enable rotation in response to device orientation.

**Comment by aacero** [comment]
+1 Having the launcher respect the orientation would make using it, on tablets especially, much more comfortable.

**Comment by SubhamTyagi** [comment]
@aacero @trevorparsons 
i also agree that launcher must respect device orientation so this will be available as soon as possible.

**Comment by Atemu** [comment]
You can already hack this functionality in by using tools like Rotation Manager to force rotation on the app.

It has a few hickups but gives an idea of how it would work.

**Comment by SubhamTyagi** [comment]
it will available in next release
@aacero @trevorparsons @Atemu
