### ISSUE TITLE
[Bug] Disappearing apps and apps not staying in Android recent menu

### ISSUE THREAD

**Issue by esmoak** [SubhamTyagi/Last-Launcher#23]
0.3.3 from F-droid

Tried doing a fresh install after removing previous version. Reboot phone, etc.
 HUAWEI
Android 8.0

Some apps disappear from the launcher after clicking on them, some launch but don’t stay in recent menu. Only way to fix is reset to default every time.

edit: It appears that locking the app size prevents them disappearing on my device. Will troubleshoot some more...

**Comment by unInstance** [comment]
same thing chiron, android pie

**Comment by Esselans** [comment]
Same. Android one (9, latest patch). Confirmed workaround is resetting to default and freezing all apps.

**Comment by IronJaeger** [comment]
Same exact thing on Android 7.1.1

**Comment by esmoak** [comment]
New version just hit  F-droid. 

Almost everything is solved.

I have not checked all apps, but for some reason RedReader from F-droid won’t stay in recents menu but everything else so far does. Not sure if there is something specific about that app, maybe something to do with being a webview wrapper?

**Comment by SubhamTyagi** [comment]
fixed in v0.6

**Comment by esmoak** [comment]
Confirmed fixed for me. Think this is also similar to #36 

Thanks again for the awesome work
