### ISSUE TITLE
Feature request: Edit app names

### ISSUE THREAD

**Issue by nussbaumer** [SubhamTyagi/Last-Launcher#3]
Many apps have long names, that clutter the list. A long press on the app name in the color/size changer to edit the name would be helpful.

**Comment by Wilker-a** [comment]
to keep it readable, having the default name or the package name shown in the info would be good for when someone forgets its original name

**Comment by SubhamTyagi** [comment]
https://github.com/SubhamTyagi/Last-Launcher/commit/c567319b4477882df425317dfd38927d95d4835c fixed
