### ISSUE TITLE
Banco inter

### ISSUE THREAD

**Issue by ralmcruz** [SubhamTyagi/Last-Launcher#34]
The app Banco Inter FC everytime after launched by Last Launcher. Only this app has this behavior.

https://play.google.com/store/apps/details?id=br.com.intermedium

**Comment by SubhamTyagi** [comment]
i didn't understand the problem could you further elaborate it

**Comment by ralmcruz** [comment]
Well, after i tap the app (banco inter) it launches and  then closes. Everytime that happens. Only happens with this specific app.

**Comment by SubhamTyagi** [comment]
This is also happen with  _miui calculator_

**Comment by SubhamTyagi** [comment]
fixed in v0.6

**Comment by ralmcruz** [comment]
Thank you very much. Solved.
