### ISSUE TITLE
Add search bar

### ISSUE THREAD

**Issue by LeSnake04** [SubhamTyagi/Last-Launcher#37]
Please add an search bar!

**Comment by chihuahua45** [comment]
Rather than a search bar, hitting home button to search would help save screen space. Correct ?

**Comment by LeSnake04** [comment]
> Rather than a search bar, hitting home button to search would help save screen space. Correct ?

Thats sounds nice. good idea

**Comment by esmoak** [comment]
If this gets implemented, I think a gesture would be better--maybe because I obsessively hit the home button and wouldn't want search popping up on accident.

Like maybe a double tap or a swipe up in blank space. Or a set tap zone in the bottom corners that can't be occupied by an app name...

**Comment by chihuahua45** [comment]
> If this gets implemented, I think a gesture would possibly be better -- maybe because I obsessively hit the home button and wouldn't want search popping up on accident.
> 
> Like maybe a double tap or a swipe up in blank space. Or a set tap zone in the bottom corners that can't be occupied by an app name...

Agreed. Gesture's better than hitting home

**Comment by chihuahua45** [comment]
@dev - Please include hidden apps in the search.

**Comment by SubhamTyagi** [comment]
fixed and available in version v0.11

**Comment by Eric3971** [comment]
> 
> 
> @dev - Please include hidden apps in the search.

Oh yes ! I want it too !
