### ISSUE TITLE
Feature request: Access to App-Info

### ISSUE THREAD

**Issue by nussbaumer** [SubhamTyagi/Last-Launcher#4]
Access to Androids App-Info is essential to any launcher. A  button [i] in the color/size changer would be most useful.
Very promising project, thanks!

**Comment by Wilker-a** [comment]
a button for quick uninstall would be nice too :3

**Comment by nussbaumer** [comment]
Uninstall is one click away in App-Info. Lets keep it simple and avoid accidental unistalls.

**Comment by OffifialMITX** [comment]
@nussbaumer Well you'll have to confirm the uninstall in it's own dialog anyway.

**Comment by SubhamTyagi** [comment]
i have push some code, in next few days it will be rolled out as i create a tag.

**Comment by Wilker-a** [comment]
@Subham just a heads-up: you can write in the commit message things like `see #4` or `fixes #4` to automatically close an issue which the commit refers to.

:3

**Comment by Wilker-a** [comment]
@Subham just a heads-up: you can write in the commit message things like `see #4` or `fixes #4` to automatically close an issue which the commit refers to.

:3

**Comment by SubhamTyagi** [comment]
@Wilker-a  i know but i doesn't want to close any issues yet. To avoid any duplication of issues, these will be closed when i create a tag release
