### ISSUE TITLE
[Feature Request] Reorder long press menu 

### ISSUE THREAD

**Issue by esmoak** [SubhamTyagi/Last-Launcher#46]
When long pressing on an app, it would be helpful if the "reset" option was on the very top or bottom so as to not accidentally press it when renaming an app. I think top would be better so it is harder to reach. 

Also, it would be helpful if frozen apps can't be reset in general. That freeze state applies to name, size, and color. 

Also, Freezed apps should probably be changed to Frozen 

Thanks for the wonderful app. I'm very excited to see you you're still working on it.

**Comment by SubhamTyagi** [comment]
also "Irrevocable Operations Item" entries could be in "red" color

👍
