### ISSUE TITLE
[Feature Request] Margin padding and alignment 

### ISSUE THREAD

**Issue by esmoak** [SubhamTyagi/Last-Launcher#47]
It would be great if there was an option to set the amount of margin on the top, bottom, left, and right, for extra unused space.

Also, an option to align all apps on the left, center, or right, as a list, would be fantastic . Edit, realized this is same as #39

- [x] Alignment
- [x] Margin or Padding

**Comment by SubhamTyagi** [comment]
https://github.com/SubhamTyagi/Last-Launcher/issues/39#issuecomment-609052392

Alignment achieved :smile:

**Comment by esmoak** [comment]
You are the best. Closing this. I will reopen if you want me to leave padding suggesting here

**Comment by SubhamTyagi** [comment]
@esmoak margin padding is in progress 😉

**Comment by SubhamTyagi** [comment]
padding... 🎁 

![1](https://user-images.githubusercontent.com/12555601/78872863-86340e00-7a67-11ea-99d0-f90c3f542b77.jpg)
