### ISSUE TITLE
Scroll up further

### ISSUE THREAD

**Issue by unInstance** [SubhamTyagi/Last-Launcher#5]
With today's screen sizes it's impossible to reach top of the display. Make it possible to scroll up further so that we can launch applications atop the screen with one hand.

**Comment by Ctrl-A-Del** [comment]
Maybe you could implement a default setting to align the apps with the bottom of the screen, instead of the top

**Comment by SubhamTyagi** [comment]
Hi @unInstance, i have implemented the padding to TOP, BOTTOM, RIGHT, LEFT, so user can adjust padding according to own needs. I hope this will be helpful. This new feature will be in version v0.8.

**Comment by unInstance** [comment]
This is super sweet but can you please increase the top padding limit from 300 to 1000?
