### ISSUE TITLE
option to run hidden apps ?

### ISSUE THREAD

**Issue by midros** [SubhamTyagi/Last-Launcher#52]
It would be very convenient to be able to start also hidden apps.

Right now you only have the option to remove them from the hidden list, but if you also have the option to run them, you could hide the ones that are rarely used

**Comment by chihuahua45** [comment]
Seconded ! The search function (when implemented) should take care of that

**Comment by midros** [comment]
great this option is already added. Thanks a lot
BUT
now when you long press on an app, in the menu that comes on, the last three options are blank.
(not visible although they work)

![Screenshot_2020-04-24-10-52-32](https://user-images.githubusercontent.com/32762300/80188673-2ec2a000-861a-11ea-8e1d-536e6361dee8.png)

**Comment by SubhamTyagi** [comment]
@midros  
Android version:??
Device:??

**Comment by SubhamTyagi** [comment]
Is this reproducible if you change Theme to other one?

**Comment by midros** [comment]
Android  version 5.1
Motorola moto g3

Same thing on all themes.
