### ISSUE TITLE
Add shortcuts to homescreen

### ISSUE THREAD

**Issue by chihuahua45** [SubhamTyagi/Last-Launcher#54]
Ability to add shortcuts to home screen from other apps like Browsers, Shortcut  Creator etc

**Comment by chihuahua45** [comment]
It's not working, dev...  I'm on app version 0.10

**Comment by SubhamTyagi** [comment]
@chihuahua45 

Older shortcuts or PWA will not be listed in launcher. 

Add some new shortcut or PWA.

**Comment by SubhamTyagi** [comment]
A serious memory leak is detected when deleting the shortcut.

**Comment by chihuahua45** [comment]
No probs, bruh.. Take your time.

**Comment by chihuahua45** [comment]
Not working, bro 😔

**Comment by ralmcruz** [comment]
I am using fennec f-droid but not been able to do create an shortcut.

![Screenshot_20200514-101240_Fennec_F-Droid](https://user-images.githubusercontent.com/53799101/81944829-a9585d00-95d3-11ea-8458-0f59d1fd4998.png)

**Comment by SubhamTyagi** [comment]
@ralmcruz 
Try the home button shortcut which is shown next to url bar in fennec

**Comment by ralmcruz** [comment]
I couldn't find it.

**Comment by spinoza-dat** [comment]
### Doesn't work for me
Android 9
Last Launcher v0.13

I manage to create the shortcuts without any error message, but they won't appear in the launcher (I don't have other launchers installed).
Any suggestion?
![IMG_20200528_120207](https://user-images.githubusercontent.com/63900993/83128294-8356b080-a0db-11ea-8765-7f024113083e.jpg)
![Screenshot_20200528-120007_Bromite](https://user-images.githubusercontent.com/63900993/83128297-83ef4700-a0db-11ea-8133-cc5ed39cca2d.png)
![Screenshot_20200528-120015_Last_Launcher](https://user-images.githubusercontent.com/63900993/83128288-818ced00-a0db-11ea-8457-4b8126f3d3df.png)

**Comment by chihuahua45** [comment]
On version 0.13.. Still not working 😔
