### ISSUE TITLE
Red popup menus items are not visible

### ISSUE THREAD

**Issue by SubhamTyagi** [SubhamTyagi/Last-Launcher#58]
Now when you long press on an app, in the menu that comes on, the last three options are blank.
(not visible although they work)

![Screenshot_2020-04-24-10-52-32](https://user-images.githubusercontent.com/32762300/80188673-2ec2a000-861a-11ea-8e1d-536e6361dee8.png)

_Originally posted by @midros in https://github.com/SubhamTyagi/Last-Launcher/issues/52#issuecomment-618863833_

**Comment by SubhamTyagi** [comment]
@midros  

could you check in this bulid if this gone

**Comment by midros** [comment]
fixed with the last update
nice!
