### ISSUE TITLE
Feature Request: color and size import / export

### ISSUE THREAD

**Issue by renyuneyun** [SubhamTyagi/Last-Launcher#6]
**Requested feature**:

Import (and export) of color (and size and everything) of apps.

**Technical approach**:

Store the information into a structured file, e.g. json. Each section (e.g. element in array) contains three elements: appId, color and size.
AppId and color are absolute values. Size can be absolute or relative, depending on the design.
When importing into the app (launcher), find matches and replace their current value with the value in the configuration file.
The un-matched apps can either remain its old value, or allow to provide a default value.

**Motivation and benefit**

A very basic use is to allow restore after big changes of the device (e.g. change device, flash rom).

But this is not the only reason. Actually a more powerful use is: users can use this feature to customize their color palette easily.

I actually wanted to color my apps in a consistent and "reasonable" way, e.g. games all in A, utils all in B, etc. Sometimes apps may belong to multiple categories, and I would like to make their color sit in-between the two (or as a percentage).
A program may be written to automatically classify the colors, and then generate the configuration file. Then the launcher takes this configuration and imports the color.

I also saw issue #2. It can be resolved by having this feature and providing another app or web app or something to generate the color configuration. Therefore this feature remains general and the app size can remain small.

- - - - - -
A little background:
I have been a user of ap15 for a long time. I really liked its idea, but I saw a lot of inconvenience of its, especially when flashing new roms. (And its pro features are not as convinent as I expected -- especially no "group" operations.)
These problems almost made me want to write a launcher myself -- but I don't have that much time, because maintaining Easer already exhausts my free time. It's so excited for me to see this app appear on f-droid.

**Comment by SubhamTyagi** [comment]
dep #28
