### ISSUE TITLE
[Quick-fix] Add android.permission.REQUEST_DELETE_PACKAGES 

### ISSUE THREAD

**Issue by ruipachecoOS** [SubhamTyagi/Last-Launcher#62]
Hi,

Since Android P deleting apps requires manifest permission "android.permission.REQUEST_DELETE_PACKAGES" no matter if you use "ACTION_DELETE" or "ACTION_UNINSTALL_PACKAGE".

source -> https://developer.android.com/reference/android/content/Intent.html#ACTION_UNINSTALL_PACKAGE

Please add it to the manifest 🗡️  :D

**Comment by ruipachecoOS** [comment]
Thanks for this app!!!

**Comment by SubhamTyagi** [comment]
Thanks
