### ISSUE TITLE
Weblate instead of Crowdin

### ISSUE THREAD

**Issue by comradekingu** [SubhamTyagi/Last-Launcher#63]
I want to provide a nb_NO translation for this, but don't want the tracking and profiling of Crowdin.
KISS, HgLauncher and others are already on Hosted Weblate. :)

**Comment by SubhamTyagi** [comment]
@comradekingu 
I have also applied for Weblate gratis support as same time as crowdin. But they process these gratis request once a month. They will take their time. Whenever weblate support is available it will be migrated to there.

**Comment by SubhamTyagi** [comment]
@comradekingu Weblate translation is ready!

**Comment by comradekingu** [comment]
@SubhamTyagi There is an issue saying
> fatal: could not read Username for 'https://github.com': terminal prompts disabled
 (128)

If you add https://hosted.weblate.org/user/kingu/ as admin in https://hosted.weblate.org/access/last-launcher/ I can try to help with any issues.
Ultimately the Crowdin one has to be closed, as the terms in it are only accepted additionally for people using it.

**Comment by SubhamTyagi** [comment]
@comradekingu 
> If you add https://hosted.weblate.org/user/kingu/ as admin in https://hosted.weblate.org/access/last-launcher/ I can try to help with any issues.

Done


>Edit: The license on Weblate is stated as "GPLv3-only", when https://github.com/SubhamTyagi/Last-Launcher/blob/master/LICENSE is GPLv3+

Done

**Comment by comradekingu** [comment]
@SubhamTyagi If you close down the Crowdin account I can contribute on Weblate without strings entering the closed Crowdin translation memory. Because of how egregious the terms of use are, to my understanding Last-Launcher can't do that with GPLv3+ strings whose copyright belongs to someone else. Delete all data from it too.

No project that has a "free" account on Crowdin can opt out of submitting strings to that translation memory, which is why it is a trap, and it is agreed to by sublicensing for each user-account on Crowdin.

Also, Crowdin is a dumpsterfire of ugly terms and service agreements, which is reason enough to clear away from it as far as possible.
https://github.com/jitsi/jitsi-meet/issues/5056#issuecomment-612239691

> We may disclose information to third parties if you consent to us doing so, as well as in the following circumstances:

> In collaboration with these third parties, we collect information about our customers, prospects and other individuals over time and across different platforms when they use these platforms or interact with them. Individuals may submit information directly on our Sites or on platforms run by third parties, or by interacting with us, our advertisements, or emails they receive from us or from third parties. We may use special tools that are commonly used for this purpose, such as cookies, pixels, and similar technologies. We may have access to databases of information collected by our business partners.

    The information we or third party collect enables us to learn what purchases the person made, what ads or content the person sees, on which ads or links the person clicks, and other actions that the person takes on our Sites, or in response to our emails, or when visiting or using third parties’ platforms.

I just quoted this part, but if you read into it, you will understand the full extent and magnitude of shady activity that goes on at Crowdin.

**Comment by SubhamTyagi** [comment]
@comradekingu i will shut down that account.

**Comment by SubhamTyagi** [comment]
Cheers @comradekingu ,
I have deleted the project and also my account from Crowdin.
