### ISSUE TITLE
[Enhancement] Brighter colours

### ISSUE THREAD

**Issue by spinoza-dat** [SubhamTyagi/Last-Launcher#65]
Some colours are very dark, like blue and purple, and therefore almost unusable with black background when display brightness is law.
It would be nice to have a wider range of bright (like pastel) colours to pick for higher contrast and readability with black background without having to use hyper-saturated ones.

May be related to #15 and #41, as a hex colour picker would solve all of these.

**Comment by SubhamTyagi** [comment]
work in progress 😄

**Comment by spinoza-dat** [comment]
Great work! Well done, thank you so much
