### ISSUE TITLE
[Enhancement] Sort by install date 

### ISSUE THREAD

**Issue by gabriel-tandil** [SubhamTyagi/Last-Launcher#67]
It would be great to be able to sort through recently installed applications

**Comment by gabriel-tandil** [comment]
It would be very useful to find newly installed applications if one does not know exactly the name (since without the visual support of an icon they are not so easy to find sometimes)

**Comment by SubhamTyagi** [comment]
may be available in next version if not then v0.14 will definitely have this.

**Comment by gabriel-tandil** [comment]
works perfect, thank you!
