### ISSUE TITLE
some issues i dealt with

### ISSUE THREAD

**Issue by disdaogitacc** [SubhamTyagi/Last-Launcher#72]
first i've got to thank you.
there's some issues i'd like to report:
1. could you please add an option to disable the search function? i know you'd been working on a fix but i don't have that many apps that i'd ever want to search for one
2. this may sound a noob question but i can't choose any font. i've tried 3 common font types(otf, ttf ,woff) but no luck so far.
![Screenshot_2020-05-22-19-42-56](https://user-images.githubusercontent.com/65776661/82683029-8417be80-9c65-11ea-8521-e688af4c5f53.png)
*i just can't select any

3. can you fix this one too?
![Screenshot_2020-05-22-19-01-51](https://user-images.githubusercontent.com/65776661/82683228-ea9cdc80-9c65-11ea-86fb-1a37151474b5.png)
*i mean the highlight over the option and make it somehow for the whole row

cheers

**Comment by spinoza-dat** [comment]
For point 1, the search function is now really less invasive. I used to have the same issue as I only have 30 apps and I don't even have to scroll.
For point 2, I suggest to create a specific [BUG] issue, I can do it myself as I have the same bug.
For point 3, again, I suggest to create a specific [Enhancement] issue.

P.S. Could you please share somehow your wallpaper? It's beautiful

**Comment by xsteadfastx** [comment]
same for me... would love to use go mono as my font. tried TTF and OFT with no luck. every file selection is grayed out.

**Comment by anibyl** [comment]
I can't select font (ttf) either, I guess this is the reason (MIME type selection is wrong or too narrow):
https://github.com/SubhamTyagi/Last-Launcher/commit/54fe1dbd2bc9b42818eb709a1088eb22e9f01d84#diff-573483ef8a36eb1707a385839b121e6aR901
@SubhamTyagi could you please comment on this?

**Comment by foldfree** [comment]
Is there a workaround for changing the font now? Anyone succeeded?

**Comment by SubhamTyagi** [comment]
@foldfree Are you still facing problem in changing the Fonts?

**Comment by btimofeev** [comment]
I cannot select the font and the backup file, they are just grayed out. Please change the mime type to `chooseFile.setType("*/*");`

**Comment by disdaogitacc** [comment]
> P.S. Could you please share somehow your wallpaper? It's beautiful
sorry for the delay. i'd lost it, today i found it and here for you:
![1689](https://user-images.githubusercontent.com/65776661/122609711-ac096980-d093-11eb-8caf-d894f1d7d270.png)
