### ISSUE TITLE
When re-enabling an app in system settings, it does not show up in the launcher

### ISSUE THREAD

**Issue by j-julian** [SubhamTyagi/Last-Launcher#75]
Title pretty much says it all.

**To reproduce:**

1. Disable an app in system settings
2. Start Last Launcher
3. Re-enable the app
4. App does not show in launcher

**Workaround:**

Updating the re-enabled app seems to add it to the launcher.

It would be great if the launcher could somehow automatically detect this. Or maybe there should be a refresh option in the menu which re-detects installed apps?

**Comment by rubyAnneB** [comment]
I've been giving this a try and was recreating the issue with mixed results. I would disable an application, navigate back to the launcher and the shortcut would still be in the launcher but would not open the app. Upon restarting the launcher, the shortcut would be gone. 

When I would re-enable the app and go back to the launcher, it would sometimes detect that it's been re-enabled, and sometimes it wouldn't. For example, when I disabled two apps and re-enabled one, the launcher would display it. Then when I enabled the other app, the launcher would fail to display it.

**Comment by rubyAnneB** [comment]
I also got this from leakCanary:
```
┬───
│ GC Root: Local variable in native code
│
├─ android.os.HandlerThread instance
│    Leaking: NO (PathClassLoader↓ is not leaking)
│    Thread name: 'LeakCanary-Heap-Dump'
│    ↓ HandlerThread.contextClassLoader
├─ dalvik.system.PathClassLoader instance
│    Leaking: NO (ShortcutUtils↓ is not leaking and A ClassLoader is never leaking)
│    ↓ PathClassLoader.runtimeInternalObjects
├─ java.lang.Object[] array
│    Leaking: NO (ShortcutUtils↓ is not leaking)
│    ↓ Object[].[132]
├─ io.github.subhamtyagi.lastlauncher.utils.ShortcutUtils class
│    Leaking: NO (a class is never leaking)
│    ↓ static ShortcutUtils.db
│                           ~~
├─ io.github.subhamtyagi.lastlauncher.utils.Database instance
│    Leaking: UNKNOWN
│    ↓ Database.mContext
│               ~~~~~~~~
╰→ io.github.subhamtyagi.lastlauncher.LauncherActivity instance
​     Leaking: YES (ObjectWatcher was watching this because io.github.subhamtyagi.lastlauncher.LauncherActivity received Activity#onDestroy() callback and Activity#mDestroyed is true)
​     key = 6ed63665-f1d7-4e2e-ab6b-86cd3ced3a44
​     watchDurationMillis = 20095
​     retainedDurationMillis = 15084

METADATA

Build.VERSION.SDK_INT: 28
Build.MANUFACTURER: Google
LeakCanary version: 2.2
App process name: io.github.subhamtyagi.lastlauncher.debug
Analysis duration: 9509 ms```

**Comment by SubhamTyagi** [comment]
Leak is due to "static reference to context"
