### ISSUE TITLE
cant select font

### ISSUE THREAD

**Issue by xsteadfastx** [SubhamTyagi/Last-Launcher#79]
i want to use a different font. when i try to select it, the file manager opens and every file is grayed out. i tried it with OTF and TTF files.

**Comment by xsteadfastx** [comment]
it looks like its the same bug as in #72.

**Comment by SubhamTyagi** [comment]
@xsteadfastx 
Could you confirm this also present in version 14?

**Comment by btimofeev** [comment]
The file selection issue has been resolved, but now when I select a font, it just doesn't apply.  I've tried downloading multiple fonts, but none are installed.

**Comment by btimofeev** [comment]
@SubhamTyagi when the user chooses a font, then you need to copy this file to the application's private directory and take the path from there. This will eliminate many problems. I may be wrong, but it seems to me that my problem (see the message above) is most likely related to the fact that on 10 android the file manager does not give the usual path to the file, but the URI. And from the private directory, we can always get the path to the file.

**Comment by niyumard** [comment]
I'm using android 10 and I can confirm that when I choose a font from my Files nothing happens.

**Comment by SubhamTyagi** [comment]
will fix in v0.17
