### ISSUE TITLE
Feature Request: show PWAs

### ISSUE THREAD

**Issue by phamvuau** [SubhamTyagi/Last-Launcher#8]
I use some apps which are installed from their website directly (Twitter for example). I would like to see them in this launcher. Thank you.

**Comment by tkarakashian** [comment]
Would these be considered "shortcuts"?  If so, agreed.  I use [Hermit](https://hermit.chimbori.com/) to replace a number of apps with their web versions to minimize junk on my phone. Would be great if I could add them to Last as well.
