### ISSUE TITLE
Use right/left swipe gesture for search

### ISSUE THREAD

**Issue by yausername** [SubhamTyagi/Last-Launcher#81]
First of all, Thanks for the amazing app!

The up/down gesture to trigger/hide search seems a bit buggy. And because it interferes with the normal scrolling it is hard to get right.
Would it make sense to have the right/left scroll gestures to trigger/hide search box?
I would be happy to send a PR if you think this is a good idea.

Thanks

**Comment by SubhamTyagi** [comment]
@yausername i agree with you best up/down swipe is hard to achieve , this interfere with scrolling, global gestures. i would be happy to merge PR request regarding this
