### ISSUE TITLE
[FTR] Home screen shortcut support...

### ISSUE THREAD

**Issue by legkamran** [SubhamTyagi/Last-Launcher#90]
Firstly I am amazed your minimalist idea! And its trully best launcher I ever used! I wanted thank you for your effort! :)

I seen this request but asking again if its possible to add such future it was really amazing...

**Comment by SubhamTyagi** [comment]
What does it mean by "Home screen shortcut"
Is this same as App shortcut such as PWA, Website Shortcuts etc. 
Or something other.. like this https://developer.android.com/guide/topics/ui/shortcuts

**Comment by legkamran** [comment]
İts when you try to create Home screen shortcut from browser... Browsers say that : Launcher not support it.

**Comment by legkamran** [comment]
![Screenshot_20200906-233326_SmartCookieWeb](https://user-images.githubusercontent.com/29841945/92333809-6e55ca00-f099-11ea-99b2-bbc500636bd2.jpg)
When I press "Add to homescreen" its giving me:

![Screenshot_20200906-233400_SmartCookieWeb](https://user-images.githubusercontent.com/29841945/92333822-83caf400-f099-11ea-9709-75ba33827091.jpg)

**Comment by SubhamTyagi** [comment]
already included
