### ISSUE TITLE
material files is not shown or searchabe 

### ISSUE THREAD

**Issue by 532910** [SubhamTyagi/Last-Launcher#91]
material files is installed, but not shown or searchable

![Screenshot_20200904-145730_Last_Launcher](https://user-images.githubusercontent.com/14617699/92238069-1fedd300-eec1-11ea-9724-38b3394faf4c.png)

https://f-droid.org/packages/me.zhanghai.android.files

**Comment by SubhamTyagi** [comment]
Is this App hide by you ?

**Comment by 532910** [comment]
of course nope

**Comment by 532910** [comment]
have you tried to install it and find?

**Comment by SubhamTyagi** [comment]
> 
> 
> have you tried to install it and find?

i will check it

**Comment by 532910** [comment]
I found it: it named just "Files".
